version: 2.1

aliases:
  - &restore-npm-cache
    name: Restore cached root node_modules
    key: npm-cache-{{ checksum "yarn.lock" }}-{{ arch }}
  - &save-npm-cache
    name: Save node_modules to cache
    key: npm-cache-{{ checksum "yarn.lock" }}-{{ arch }}
    paths:
      - node_modules

defaults: &defaults
  docker:
    - image: node:10

restore_npm_cache: &restore_npm_cache
  restore_cache: *restore-npm-cache

save_npm_cache: &save_npm_cache
  save_cache: *save-npm-cache

jobs:
  install_dependencies_and_lint:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - run: yarn install
      - *save_npm_cache
      - run:
          name: eslint
          command: yarn lintFormat

workflows:
  build_and_test_flow:
    jobs:
      - install_dependencies_and_lint
