version: 2.1

aliases:
  - &restore-yarn-cache
    name: Restore cached root node_modules
    key: yarn-cache-{{ checksum "yarn.lock" }}-{{ arch }}
  - &save-yarn-cache
    name: Save node_modules to cache
    key: yarn-cache-{{ checksum "yarn.lock" }}-{{ arch }}
    paths:
      - node_modules

defaults: &defaults
  docker:
    - image: node:10

restore_yarn_cache: &restore_yarn_cache
  restore_cache: *restore-yarn-cache

save_yarn_cache: &save_yarn_cache
  save_cache: *save-yarn-cache

jobs:
  install_dependencies_and_lint:
    <<: *defaults
    steps:
      - checkout
      - *restore_yarn_cache
      - run: yarn install
      - *save_yarn_cache
      - run:
          name: eslint
          command: yarn lintFormat

workflows:
  build_and_test_flow:
    jobs:
      - install_dependencies_and_lint
